{{- if .Values.replicationJob.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-replication-job
  labels:
    app: {{ template "osm-seed.name" . }}
    component: replication-job
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
    spec:
      containers:
        - name: {{ .Release.Name }}-replication-job-deployment
          image: {{ .Values.replicationJob.image.name }}:{{ .Values.replicationJob.image.tag }}
          command: ['./start.sh']
          {{- if .Values.replicationJob.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.replicationJob.resources.requests.memory }}
              cpu: {{ .Values.replicationJob.resources.requests.cpu }}
            limits:
              memory: {{ .Values.replicationJob.resources.limits.memory }}
              cpu: {{ .Values.replicationJob.resources.limits.cpu }}
          {{- end }}
          env:
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-db
            - name: POSTGRES_DB
              value: {{ .Values.db.env.POSTGRES_DB }}
            - name: POSTGRES_PASSWORD
              value: {{ quote .Values.db.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_USER
              value: {{ .Values.db.env.POSTGRES_USER }}
            - name: REPLICATION_FOLDER
              value: /replication/minute
            - name: CLOUDPROVIDER
              value: {{ .Values.cloudProvider }}
            # In case cloudProvider=aws
            {{- if eq .Values.cloudProvider "aws" }}
            - name: AWS_S3_BUCKET
              value: {{ .Values.AWS_S3_BUCKET }}
            {{- end }}
            # In case cloudProvider=gcp
            {{- if eq .Values.cloudProvider "gcp" }}
            - name: GCP_STORAGE_BUCKET
              value: {{ .Values.GCP_STORAGE_BUCKET }}
            {{- end }}
              # Memory optimization for osmosis
            {{- if .Values.replicationJob.resources.enabled }}
            - name: MEMORY_JAVACMD_OPTIONS
              value: {{ .Values.replicationJob.resources.requests.memory | default "2Gi" | quote}}
            {{- end }}
      {{- if .Values.replicationJob.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.replicationJob.nodeSelector.label_key }} : {{ .Values.replicationJob.nodeSelector.label_value }}
      {{- end }}
{{- end }}