apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-planet-dump-job
  labels:
    app: {{ template "osm-seed.name" . }}
    component: planet-dump-job
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  schedule: {{ quote .Values.planetDump.schedule }}
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}-planet-dump-job
            image: {{ .Values.planetDump.image }}:{{ .Values.osmSeedVersion }}
            command: ['./start.sh']
            env:
              - name: POSTGRES_HOST
                value: {{ .Release.Name }}-db
              - name: POSTGRES_DB
                value: {{ .Values.db.env.POSTGRES_DB }}
              - name: POSTGRES_PASSWORD
                value: {{ quote .Values.db.env.POSTGRES_PASSWORD }}
              - name: POSTGRES_USER
                value: {{ .Values.db.env.POSTGRES_USER }}
              {{- if .Values.backupStorage.aws.enabled }}
              - name: STORAGE
                value: S3
              # - name: AWS_ACCESS_KEY_ID
              #   value: {{ .Values.backupStorage.aws.env.AWS_ACCESS_KEY_ID }}
              # - name: AWS_SECRET_ACCESS_KEY
              #   value: {{ .Values.backupStorage.aws.env.AWS_SECRET_ACCESS_KEY }}
              - name: AWS_DEFAULT_REGION
                value: {{ .Values.backupStorage.aws.env.AWS_DEFAULT_REGION }}
              - name: S3_OSM_PATH
                value: {{ .Values.backupStorage.aws.env.S3_OSM_PATH }}
              {{- end }}
              {{- if .Values.backupStorage.google.enabled }}
              - name: STORAGE
                value: GS
              - name: GCLOUD_PROJECT
                value: {{ .Values.backupStorage.google.env.GCLOUD_PROJECT }}
              - name: GCLOUD_SERVICE_KEY
                value: {{ .Values.backupStorage.google.env.GCLOUD_SERVICE_KEY }}
              - name: GS_OSM_PATH
                value: {{ .Values.backupStorage.google.env.GS_OSM_PATH }}
              {{- end }}
          restartPolicy: Never
      backoffLimit: 3
