{{- if .Values.idEditor.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osm-seed.fullname" . }}-id-editor
  labels:
    app: {{ template "osm-seed.name" . }}
    component: id-editor-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.idEditor.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-id-editor
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-id-editor
    spec:
      containers:
        - name: {{ .Chart.Name }}-id-editor
          image: "{{ .Values.idEditor.image }}:{{ .Values.osmSeedVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.idEditor.env.ID_EDITOR_PORT }}
              protocol: TCP
          {{- if .Values.idEditor.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.idEditor.resources.requests.memory }}
              cpu: {{ .Values.idEditor.resources.requests.cpu }}
            limits:
              memory: {{ .Values.idEditor.resources.limits.memory }}
              cpu: {{ .Values.idEditor.resources.limits.cpu }}
          {{- end }}
          env:
            - name: OAUTH_CONSUMER_KEY
              value: {{ .Values.idEditor.env.OAUTH_CONSUMER_KEY }}
            - name: OAUTH_SECRET
              value: {{ .Values.idEditor.env.OAUTH_SECRET }}
            - name: SERVER_URL
              value: {{ .Values.idEditor.env.OSM_API_DOMAIN }}
            - name: SERVER_PROTOCOL
              value : {{ .Values.idEditor.env.OSM_API_PROTOCOL }}
      {{- if .Values.idEditor.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.idEditor.nodeSelector.label_key }} : {{ .Values.idEditor.nodeSelector.label_value }}
      {{- end }}
{{- end }}
